### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by FredrikNoren** [dche/glm-rs#9]
The link to the documentation gives a 404

**Comment by dche** [comment]
Sorry about that. Currently to read the docs you have to clone the project and run `cargo doc` locally.

I tried 3 methods of hosting create docs,
- The doc uploading functionality of `rust-ci.org` do not work at most time,
- `rustdox.com` is broken by a crate with hyphen in its name,
- `gh-pages` is too complex and I don't want to touch it.

I will fix this once we have better ways to host docs.

**Comment by FredrikNoren** [comment]
Cool, added a PR to fix the doc: https://github.com/dche/glm-rs/pull/10

**Comment by dche** [comment]
Reopen and really fix it.
